MONGODB_URI = "mongodb://localhost:27017/"
MONGODB_DB = "pokemongo"
MONGODB_POKEMONS_COLLECTION = "pokemons"
MONGODB_PLAYERS_COLLECTION = "players"

REDIS_URI = "redis://localhost"

MAX_POKEMON_CAPTURED = 300
MAX_LEVEL = 40
POWER_UP_COEFFICIENT = 1.025
